import { StoreId, StoreInfo } from './types';

export const STORES: Record<StoreId, StoreInfo> = {
  central: {
    id: 'central',
    name: 'Central Madeirense',
    shortName: 'Central',
    color: 'text-blue-900 dark:text-blue-200',
    bgColor: 'bg-blue-50/80 dark:bg-blue-950/40',
    borderColor: 'border-blue-200 dark:border-blue-800',
    logoText: 'CM',
    url: 'https://tucentralonline.com/La-Alameda-50/',
    currencyNative: 'USD',
  },
  gama: {
    id: 'gama',
    name: 'Gama Supermercados',
    shortName: 'Gama',
    color: 'text-blue-900 dark:text-blue-200',
    bgColor: 'bg-blue-50/80 dark:bg-blue-950/40',
    borderColor: 'border-blue-200 dark:border-blue-800',
    logoText: 'GAMA',
    url: 'https://gamaenlinea.com/es/',
    currencyNative: 'USD',
  },
  plazas: {
    id: 'plazas',
    name: "Automercados Plaza's",
    shortName: "Plaza's",
    color: 'text-blue-900 dark:text-blue-200',
    bgColor: 'bg-blue-50/80 dark:bg-blue-950/40',
    borderColor: 'border-blue-200 dark:border-blue-800',
    logoText: "PLAZA'S",
    url: 'https://vallearriba.elplazas.com',
    currencyNative: 'USD',
  },
  kalea: {
    id: 'kalea',
    name: 'Kalea Market',
    shortName: 'Kalea',
    color: 'text-blue-900 dark:text-blue-200',
    bgColor: 'bg-blue-50/80 dark:bg-blue-950/40',
    borderColor: 'border-blue-200 dark:border-blue-800',
    logoText: 'KALEA',
    url: 'https://www.kaleamarket.com',
    currencyNative: 'VES',
  },
  farmatodo: {
    id: 'farmatodo',
    name: 'Farmatodo',
    shortName: 'Farmatodo',
    color: 'text-blue-900 dark:text-blue-200',
    bgColor: 'bg-blue-50/80 dark:bg-blue-950/40',
    borderColor: 'border-blue-200 dark:border-blue-800',
    logoText: 'FARMATODO',
    url: 'https://www.farmatodo.com.ve',
    currencyNative: 'VES',
  },
};

export const POPULAR_SEARCHES = [
  'Harina PAN',
  'Leche Completa 1L',
  'Arroz Blanco 1kg',
  'Aceite Mazeite',
  'Pasta Primor 1kg',
  'Café Fama de América',
  'Azúcar 1kg',
  'Atún Margarita',
  'Queso Paisa',
  'Mantequilla Mavesa 500g',
  'Nutella',
  'Coca Cola 1L',
];
